[mgr]
linemode = "size"
ratio = [0, 5, 5]

[[manager.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[manager.prepend_keymap]]
on = "o"
run = "plugin open-with-cmd --args=block"
desc = "Open with command in the terminal"

[preview]
tab_size        = 2
max_width       = 2400
max_height      = 3600
image_quality   = 75

