[opener]
edit = [
  { run = 'nvim "$@"', block = true },
]
read = [
  { run = 'open "$@"', desc = "Open" }
]

[open]
prepend_rules = [
  { name = "*.pdf", use = "read" },
  { name = "*.qmd", use = "edit" }
]

[manager]
linemode = "size"
